task: decompose_lockd

# Dataset setup

imagenet_root_dir: /nas/datasets/vision/ImageNet/pod_download/data/fix
trn_imagenet_classes_fname: /nas/datasets/vision/ImageNet/pod_download/data/train_es.txt
val_imagenet_classes_fname: /nas/datasets/vision/ImageNet/pod_download/data/val.txt
batch_size: 128
normalization: imagenet
input_h_w: [224, 224]

# Model setup

decompose_model_name: timm.resnet18.a2_in1k

# Decomposition setup

proportion_threshold: 10.0
blacklisted_modules: []
lmbda: 1.0
nsr_threshold: 0.1

# Training setup

lr: 0.001
lr_t_warmup:  0ep
max_duration: 10ba
optimizer: Adam
precision: amp_fp16
alg_channel_last: True
alg_gradient_clipping_type: Null

compile_config:
    mode: default
