task: finetune

# Dataset setup

imagenet_root_dir: /nas/datasets/vision/ImageNet/pod_download/data/fix
trn_imagenet_classes_fname: /nas/datasets/vision/ImageNet/pod_download/data/train_es.txt
val_imagenet_classes_fname: /nas/datasets/vision/ImageNet/pod_download/data/val.txt
batch_size: 8
normalization: imagenet
input_h_w: [224, 224]


# Model setup

decompose_model_name: timm.efficientformerv2_s2.snap_dist_in1k
decompose_config: tmp/decompose_config.json
decompose_state_dict: tmp/decompose_state_dict.pt
proportion_threshold: 0.8
blacklisted_modules:
  - stem.conv1.conv
  - head
  - head_dist

# Training setup

lr: 0.0015
lr_t_warmup: 5ep
max_duration: 200ep
input_h_w: [224, 224]
optimizer: SGD
precision: null
compile_config:
    mode: default
