task: finetune

# Dataset setup

imagenet_root_dir: /nas/datasets/vision/ImageNet/pod_download/data/fix
trn_imagenet_classes_fname: /nas/datasets/vision/ImageNet/pod_download/data/train_es.txt
val_imagenet_classes_fname: /nas/datasets/vision/ImageNet/pod_download/data/val.txt
batch_size: 8
normalization: imagenet
input_h_w: [224, 224]


# Model setup

decompose_model_name: timm.swinv2_cr_tiny_ns_224.sw_in1k
decompose_config: tmp_inp/decompose_config.json
decompose_state_dict: tmp_inp/decompose_state_dict.pt
proportion_threshold: 0.8
blacklisted_modules:
  - patch_embed.proj
  - head.fc

# Training setup

lr: 0.0015
lr_t_warmup: 5ep
max_duration: 200ep
optimizer: SGD
precision: amp_fp16
alg_channel_last: True
alg_gradient_clipping_type: Null

compile_config:
    mode: default
