task: "decompose_dwain"

# Model specification

decomposed_model_name: "microsoft/phi-2"
decomposed_model_revision: "main"
decomposed_model_enable_gradient_checkpointing: true
decomposed_model_dtype: "torch.bfloat16"


# Data handling params

decomposition_data_name: "alpaca.train"
decomposition_data_separator: "\n\n" # Normal pythonic string, no extra escaping needed
decomposition_data_max_length: 2048
decomposition_data_batch_size: 1

perplexity_data_name: "wikitext2.test"
perplexity_data_separator: "\n\n"  # Normal pythonic string, no extra escaping needed
perplexity_data_max_length: 2048
perplexity_data_batch_size: 1

# Decomposition params

decompose_in_float64: true
num_data_steps: 2048
num_metric_steps: 32
trade_off_factor: 0.5
proportion_threshold: 0.75
ppl_diff_threshold: 0.005
min_proportion: 0.25
nsr_final_threshold: 1.0
min_rank: 4
precomputing_covariance_num_splits: 8


# Fintetuning params

finetuning_run: true
finetuning_use_lora: true
finetuning_lora_min_rank: 32
finetuning_lr: 0.0001
finetuning_num_steps: 10
finetuning_num_last_finetuned_modules: 8
finetuning_use_rank_pattern: false

# lm_eval evaluation params
lm_eval_tasks:
  - arc_challenge
  - arc_easy
  - piqa
  - hellaswag
  - winogrande

blacklisted_module_names:
  - lm_head
  #- model.layers.0.self_attn.q_proj
  #- model.layers.0.self_attn.k_proj
  #- model.layers.0.self_attn.v_proj
  #- model.layers.0.self_attn.dense
  #- model.layers.0.mlp.fc1
  #- model.layers.0.mlp.fc2
  #- model.layers.1.self_attn.q_proj
  #- model.layers.1.self_attn.k_proj
  #- model.layers.1.self_attn.v_proj
  #- model.layers.1.self_attn.dense
  #- model.layers.1.mlp.fc1
  #- model.layers.1.mlp.fc2
  # - model.layers.2.self_attn.q_proj
  # - model.layers.2.self_attn.k_proj
  # - model.layers.2.self_attn.v_proj
  # - model.layers.2.self_attn.dense
  # - model.layers.2.mlp.fc1
  # - model.layers.2.mlp.fc2
  # - model.layers.3.self_attn.q_proj
  # - model.layers.3.self_attn.k_proj
  # - model.layers.3.self_attn.v_proj
  # - model.layers.3.self_attn.dense
  # - model.layers.3.mlp.fc1
  # - model.layers.3.mlp.fc2
  # - model.layers.4.self_attn.q_proj
  # - model.layers.4.self_attn.k_proj
  # - model.layers.4.self_attn.v_proj
  # - model.layers.4.self_attn.dense
  # - model.layers.4.mlp.fc1
  # - model.layers.4.mlp.fc2
  # - model.layers.5.self_attn.q_proj
  # - model.layers.5.self_attn.k_proj
  # - model.layers.5.self_attn.v_proj
  # - model.layers.5.self_attn.dense
  # - model.layers.5.mlp.fc1
  # - model.layers.5.mlp.fc2
  # - model.layers.6.self_attn.q_proj
  # - model.layers.6.self_attn.k_proj
  # - model.layers.6.self_attn.v_proj
  # - model.layers.6.self_attn.dense
  # - model.layers.6.mlp.fc1
  # - model.layers.6.mlp.fc2
  # - model.layers.7.self_attn.q_proj
  # - model.layers.7.self_attn.k_proj
  # - model.layers.7.self_attn.v_proj
  # - model.layers.7.self_attn.dense
  # - model.layers.7.mlp.fc1
  # - model.layers.7.mlp.fc2
  # - model.layers.8.self_attn.q_proj
  # - model.layers.8.self_attn.k_proj
  # - model.layers.8.self_attn.v_proj
  # - model.layers.8.self_attn.dense
  # - model.layers.8.mlp.fc1
  # - model.layers.8.mlp.fc2
  # - model.layers.9.self_attn.q_proj
  # - model.layers.9.self_attn.k_proj
  # - model.layers.9.self_attn.v_proj
  # - model.layers.9.self_attn.dense
  # - model.layers.9.mlp.fc1
  # - model.layers.9.mlp.fc2
  # - model.layers.10.self_attn.q_proj
  # - model.layers.10.self_attn.k_proj
  # - model.layers.10.self_attn.v_proj
  # - model.layers.10.self_attn.dense
  # - model.layers.10.mlp.fc1
  # - model.layers.10.mlp.fc2
  # - model.layers.11.self_attn.q_proj
  # - model.layers.11.self_attn.k_proj
  # - model.layers.11.self_attn.v_proj
  # - model.layers.11.self_attn.dense
  # - model.layers.11.mlp.fc1
  # - model.layers.11.mlp.fc2
  # - model.layers.12.self_attn.q_proj
  # - model.layers.12.self_attn.k_proj
  # - model.layers.12.self_attn.v_proj
  # - model.layers.12.self_attn.dense
  # - model.layers.12.mlp.fc1
  # - model.layers.12.mlp.fc2
  # - model.layers.13.self_attn.q_proj
  # - model.layers.13.self_attn.k_proj
  # - model.layers.13.self_attn.v_proj
  # - model.layers.13.self_attn.dense
  # - model.layers.13.mlp.fc1
  # - model.layers.13.mlp.fc2
  # - model.layers.14.self_attn.q_proj
  # - model.layers.14.self_attn.k_proj
  # - model.layers.14.self_attn.v_proj
  # - model.layers.14.self_attn.dense
  # - model.layers.14.mlp.fc1
  # - model.layers.14.mlp.fc2
  # - model.layers.15.self_attn.q_proj
  # - model.layers.15.self_attn.k_proj
  # - model.layers.15.self_attn.v_proj
  # - model.layers.15.self_attn.dense
  # - model.layers.15.mlp.fc1
  # - model.layers.15.mlp.fc2
  # - model.layers.16.self_attn.q_proj
  # - model.layers.16.self_attn.k_proj
  # - model.layers.16.self_attn.v_proj
  # - model.layers.16.self_attn.dense
  # - model.layers.16.mlp.fc1
  # - model.layers.16.mlp.fc2
  # - model.layers.17.self_attn.q_proj
  # - model.layers.17.self_attn.k_proj
  # - model.layers.17.self_attn.v_proj
  # - model.layers.17.self_attn.dense
  # - model.layers.17.mlp.fc1
  # - model.layers.17.mlp.fc2
  # - model.layers.18.self_attn.q_proj
  # - model.layers.18.self_attn.k_proj
  # - model.layers.18.self_attn.v_proj
  # - model.layers.18.self_attn.dense
  # - model.layers.18.mlp.fc1
  # - model.layers.18.mlp.fc2
  # - model.layers.19.self_attn.q_proj
  # - model.layers.19.self_attn.k_proj
  # - model.layers.19.self_attn.v_proj
  # - model.layers.19.self_attn.dense
  # - model.layers.19.mlp.fc1
  # - model.layers.19.mlp.fc2
  # - model.layers.20.self_attn.q_proj
  # - model.layers.20.self_attn.k_proj
  # - model.layers.20.self_attn.v_proj
  # - model.layers.20.self_attn.dense
  # - model.layers.20.mlp.fc1
  # - model.layers.20.mlp.fc2
  # - model.layers.21.self_attn.q_proj
  # - model.layers.21.self_attn.k_proj
  # - model.layers.21.self_attn.v_proj
  # - model.layers.21.self_attn.dense
  # - model.layers.21.mlp.fc1
  # - model.layers.21.mlp.fc2
  # - model.layers.22.self_attn.q_proj
  # - model.layers.22.self_attn.k_proj
  # - model.layers.22.self_attn.v_proj
  # - model.layers.22.self_attn.dense
  # - model.layers.22.mlp.fc1
  # - model.layers.22.mlp.fc2
  # - model.layers.23.self_attn.q_proj
  # - model.layers.23.self_attn.k_proj
  # - model.layers.23.self_attn.v_proj
  # - model.layers.23.self_attn.dense
  # - model.layers.23.mlp.fc1
  # - model.layers.23.mlp.fc2
  # - model.layers.24.self_attn.q_proj
  # - model.layers.24.self_attn.k_proj
  # - model.layers.24.self_attn.v_proj
  # - model.layers.24.self_attn.dense
  # - model.layers.24.mlp.fc1
  # - model.layers.24.mlp.fc2
  # - model.layers.25.self_attn.q_proj
  # - model.layers.25.self_attn.k_proj
  # - model.layers.25.self_attn.v_proj
  # - model.layers.25.self_attn.dense
  # - model.layers.25.mlp.fc1
  # - model.layers.25.mlp.fc2
  # - model.layers.26.self_attn.q_proj
  # - model.layers.26.self_attn.k_proj
  # - model.layers.26.self_attn.v_proj
  # - model.layers.26.self_attn.dense
  # - model.layers.26.mlp.fc1
  # - model.layers.26.mlp.fc2
  # - model.layers.27.self_attn.q_proj
  # - model.layers.27.self_attn.k_proj
  # - model.layers.27.self_attn.v_proj
  # - model.layers.27.self_attn.dense
  # - model.layers.27.mlp.fc1
  # - model.layers.27.mlp.fc2
  # - model.layers.28.self_attn.q_proj
  # - model.layers.28.self_attn.k_proj
  # - model.layers.28.self_attn.v_proj
  # - model.layers.28.self_attn.dense
  # - model.layers.28.mlp.fc1
  # - model.layers.28.mlp.fc2
  # - model.layers.29.self_attn.q_proj
  # - model.layers.29.self_attn.k_proj
  # - model.layers.29.self_attn.v_proj
  # - model.layers.29.self_attn.dense
  # - model.layers.29.mlp.fc1
  # - model.layers.29.mlp.fc2
  # - model.layers.30.self_attn.q_proj
  # - model.layers.30.self_attn.k_proj
  # - model.layers.30.self_attn.v_proj
  # - model.layers.30.self_attn.dense
  # - model.layers.30.mlp.fc1
  # - model.layers.30.mlp.fc2
  # - model.layers.31.self_attn.q_proj
  # - model.layers.31.self_attn.k_proj
  # - model.layers.31.self_attn.v_proj
  # - model.layers.31.self_attn.dense
  # - model.layers.31.mlp.fc1
  # - model.layers.31.mlp.fc2
